-- Migration: 001_create_batches_tables.sql
-- Module: batches
-- Purpose: Create all database objects required by app/modules/batches/repository.py.
--
-- This migration is idempotent: every statement uses IF NOT EXISTS so that
-- re-running the file (e.g. after a partial failure) does not raise errors.
-- The migration runner (scripts/run_migration.py) also tracks applied files in
-- public.schema_migrations and skips already-applied migrations, providing a
-- second layer of idempotency protection.

-- -------------------------------------------------------------------------
-- Schema
-- -------------------------------------------------------------------------
-- Create the batches schema if it does not already exist.
-- Having a dedicated schema per module is the core of the isolation strategy:
--   - Each module's application role (batches_app) has privileges ONLY on
--     its own schema. A bug in another module cannot accidentally query or
--     modify batches data because the database will reject the connection.
--   - Schema creation is idempotent and harmless to repeat.
CREATE SCHEMA IF NOT EXISTS batches;

-- -------------------------------------------------------------------------
-- Extension
-- -------------------------------------------------------------------------
-- pgcrypto provides gen_random_uuid(), which generates a version-4 UUID.
-- PostgreSQL 13+ includes gen_random_uuid() as a built-in without pgcrypto,
-- but enabling the extension here ensures compatibility with older versions
-- and is idempotent on newer versions.
-- The extension is created in the default (public) schema so it is accessible
-- to all roles without schema qualification.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -------------------------------------------------------------------------
-- Table: batches.batches
-- -------------------------------------------------------------------------
-- Central table for broiler batch records. One row = one grow-out cycle
-- (from chick placement to sale/archiving).
CREATE TABLE IF NOT EXISTS batches.batches (
    -- id: UUID primary key generated server-side.
    -- Using UUID instead of SERIAL/BIGINT has two benefits:
    --   1. IDs can be generated by the application without a DB round-trip
    --      (for insert-then-reference patterns).
    --   2. IDs are not guessable/sequential, which reduces IDOR risk.
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- batch_name: human-readable label set by the farmer (e.g. "Batch A March 2026").
    -- TEXT (unlimited length) rather than VARCHAR(N) because PostgreSQL stores
    -- short strings inline regardless of declared length, and artificial limits
    -- cause migration pain when they are wrong.
    batch_name TEXT NOT NULL,

    -- breed: broiler breed name (e.g. "Cobb 500", "Ross 308").
    -- Free-text rather than a FK to a breeds table to avoid requiring a
    -- breeds migration and allow flexibility for regional/custom breeds.
    breed      TEXT NOT NULL,

    -- quantity: number of chicks placed at the start of the batch.
    -- CHECK (quantity > 0) prevents nonsensical zero or negative placements
    -- that would cause division-by-zero in FCR and mortality rate calculations.
    quantity   INTEGER NOT NULL CHECK (quantity > 0),

    -- start_date: calendar date the chicks arrived (DATE, not TIMESTAMPTZ).
    -- DATE is used instead of TIMESTAMPTZ because the exact time of chick
    -- placement is not meaningful — only the day matters for age calculations.
    start_date DATE NOT NULL,

    -- end_date: the date the batch was closed (birds sold or batch ended).
    -- NULL while the batch is still active; set when status transitions to
    -- "closed". Using DATE (not TIMESTAMPTZ) matches start_date so that
    -- age_days = end_date - start_date is a simple integer subtraction in SQL.
    end_date   DATE,

    -- status: lifecycle state of the batch.
    -- The CHECK constraint ensures only valid string values are stored.
    -- Directional transition rules (active → closed → archived) are enforced
    -- by the service layer (VALID_TRANSITIONS in service.py), not here —
    -- CHECK cannot enforce direction, only valid values.
    --   active:   chicks are on the farm and being managed.
    --   closed:   birds have been sold or the cycle has ended.
    --   archived: historical record, no longer actively managed.
    status     TEXT NOT NULL DEFAULT 'active' CHECK (status IN
    ('active', 'closed', 'archived')),

    -- Performance metrics — updated incrementally by repository.update_performance().
    -- Stored as NUMERIC (exact decimal) rather than FLOAT to avoid floating-point
    -- precision loss when accumulating many small feed increments. asyncpg maps
    -- NUMERIC to Python Decimal automatically.

    -- total_feed_kg: cumulative kilograms of feed consumed by the batch.
    -- Starts at 0 and is incremented each time a feed log is recorded.
    -- NUMERIC(10,2): up to 99,999,999.99 kg — far beyond any realistic flock.
    total_feed_kg  NUMERIC(10,2) NOT NULL DEFAULT 0,

    -- mortality_count: cumulative number of bird deaths in this batch.
    -- Starts at 0 and is incremented each time a mortality event is recorded.
    mortality_count INTEGER NOT NULL DEFAULT 0,

    -- Soft delete: rows are never physically deleted. Instead, deleted_at is
    -- set to the deletion timestamp. All SELECT queries filter `deleted_at IS NULL`
    -- to exclude deleted rows. This preserves historical data for audit trails
    -- and makes accidental deletions recoverable without database backups.
    deleted_at  TIMESTAMPTZ,

    -- Audit timestamps: both are set automatically by the database.
    -- updated_at is set to NOW() by every UPDATE statement in repository.py;
    -- there is no trigger — the application is responsible for maintaining it.
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- Indexes
-- -------------------------------------------------------------------------

-- idx_batches_status: partial index on status for non-deleted rows.
-- Accelerates the common query pattern in list_all and count_all:
--     WHERE deleted_at IS NULL AND ($1::text IS NULL OR status = $1)
-- The partial index (WHERE deleted_at IS NULL) is smaller than a full index
-- and only covers the rows actually returned by queries, making it faster
-- and cheaper to maintain on INSERT/UPDATE.
CREATE INDEX IF NOT EXISTS idx_batches_status
   ON batches.batches(status)
   WHERE deleted_at IS NULL;

-- idx_batches_start_date: partial index on start_date (descending) for non-deleted rows.
-- Accelerates the ORDER BY start_date DESC clause in list_all. Without this
-- index, PostgreSQL would perform a full table scan and sort — acceptable for
-- small datasets but slow as the table grows. Descending order matches the
-- query's sort direction, so PostgreSQL can use the index directly without
-- an extra sort step.
CREATE INDEX IF NOT EXISTS idx_batches_start_date
   ON batches.batches(start_date DESC)
   WHERE deleted_at IS NULL;
