"""Domain model dataclasses for the batches module.

DATACLASS vs PYDANTIC MODEL — why use dataclasses here?
---------------------------------------------------------
Pydantic models are used at the HTTP boundary (schemas.py) because they
perform input validation, type coercion, and JSON serialisation. Inside
the application the service and repository layers work with *trusted* data
that has already been validated by PostgreSQL constraints and Pydantic
request schemas. Using plain dataclasses for that internal data:

  - Is faster: no Pydantic validators run when constructing from a DB row.
  - Is explicit: the fact that a Batch came from the database (not from
    user input) is visible in the type — BatchResponse (Pydantic) vs
    Batch (dataclass).
  - Avoids accidental serialisation: a dataclass cannot be accidentally
    returned directly from a FastAPI route handler; the router must
    explicitly call BatchResponse.model_validate(batch) to produce the
    HTTP response.

The mapping between asyncpg.Record fields and dataclass fields is
centralised in the `from_row` class method on each dataclass, so if a
column is renamed in the database there is exactly one place to update.
"""
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from uuid import UUID

import asyncpg


@dataclass
class Batch:
    """Internal representation of a single broiler batch row.

    Field names are intentionally identical to the column names returned
    by every SELECT and RETURNING clause in repository.py. This 1-to-1
    mapping means `from_row` can be written without renaming, and any
    mismatch between the SQL column list and this dataclass raises a
    KeyError immediately rather than silently producing None values.

    Fields:
        id:              UUID primary key, generated by PostgreSQL gen_random_uuid().
        batch_name:      Human-readable label given by the farmer (e.g. "Batch A March").
        breed:           Broiler breed name (e.g. "Cobb 500", "Ross 308").
        quantity:        Number of chicks placed at the start of the batch.
                         Must be > 0 (enforced by a CHECK constraint in the DB).
        start_date:      The calendar date chicks were placed. Stored as PostgreSQL
                         DATE; asyncpg returns it as a Python datetime.date.
        end_date:        The date the batch was closed/sold. None while the batch
                         is still active.
        status:          Lifecycle state: "active" → "closed" → "archived".
                         Transitions are enforced by service.py VALID_TRANSITIONS.
        total_feed_kg:   Cumulative kilograms of feed consumed, updated incrementally
                         by update_performance(). Stored as NUMERIC(10,2) →
                         Python Decimal to preserve precision.
        mortality_count: Cumulative number of bird deaths, also updated incrementally.
        created_at:      Row creation timestamp (PostgreSQL TIMESTAMPTZ, UTC).
        updated_at:      Last-modified timestamp, set to NOW() by every UPDATE query.
    """
    id: UUID
    batch_name: str
    breed: str
    quantity: int
    start_date: date
    end_date: date | None
    status: str
    total_feed_kg: Decimal
    mortality_count: int
    created_at: datetime
    updated_at: datetime

    @classmethod
    def from_row(cls, row: asyncpg.Record) -> "Batch":
        """Construct a Batch from an asyncpg result row.

        asyncpg.Record supports dict-like key access (row["column_name"]).
        Centralising the mapping here means:
          - Repository methods stay concise: `return Batch.from_row(row)`.
          - Column renames require one change here, not in every query method.
          - Tests can pass a plain dict (or a mock Record) to verify mapping
            logic independently of the SQL query.

        The explicit field list (rather than `**dict(row)`) ensures that a
        schema change that adds an *extra* column to the SELECT does not
        silently succeed and produce an unexpected extra attribute — it will
        raise a TypeError, surfacing the mismatch immediately.
        """
        return cls(
            id=row["id"],
            batch_name=row["batch_name"],
            breed=row["breed"],
            quantity=row["quantity"],
            start_date=row["start_date"],
            end_date=row["end_date"],
            status=row["status"],
            total_feed_kg=row["total_feed_kg"],
            mortality_count=row["mortality_count"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )


@dataclass
class BatchSummary:
    """Read-model dataclass for the computed batch summary endpoint.

    Unlike Batch (which mirrors a single table row), BatchSummary contains
    fields that are *derived* by the SQL query in repository.get_summary:

        initial_quantity:   Alias for quantity at the time of placement.
        surviving_birds:    quantity - mortality_count (computed in SQL).
        fcr:                Feed Conversion Ratio = total_feed_kg / surviving_birds.
                            NULL when surviving_birds = 0 (would be division by zero).
                            Rounded to 3 decimal places.
                            Lower FCR = more feed-efficient flock (industry target < 2.0).
        mortality_rate_pct: mortality_count / quantity * 100, rounded to 2 dp.
                            NULL when quantity = 0 (defensive NULLIF guard).
        age_days:           Days since start_date (or until end_date if closed),
                            computed as (COALESCE(end_date, CURRENT_DATE) - start_date)::int.

    Field names here must exactly match the SQL column aliases in
    repository.BatchRepository.get_summary, because from_row uses the
    generic `**{k: row[k] for k in row}` unpacking (see below).
    """
    id: UUID
    batch_name: str
    breed: str
    initial_quantity: int
    mortality_count: int
    surviving_birds: int
    total_feed_kg: Decimal
    start_date: date
    end_date: date | None
    status: str
    fcr: Decimal | None          # Feed Conversion Ratio; None when no surviving birds
    mortality_rate_pct: Decimal | None  # Percentage of flock that died; None when qty = 0
    age_days: int

    @classmethod
    def from_row(cls, row: asyncpg.Record) -> "BatchSummary":
        """Construct a BatchSummary from an asyncpg result row using dict unpacking.

        Unlike Batch.from_row (which maps fields explicitly), this method uses
        `**{k: row[k] for k in row}` — iterating over all column names returned
        by the row and passing them as keyword arguments to the dataclass.

        This is intentional for a read-model with many computed columns: adding
        a new computed field to the SQL query and the dataclass simultaneously
        does not require updating this method. The trade-off is that a column
        name mismatch between SQL and the dataclass raises a TypeError at runtime
        ("unexpected keyword argument") rather than a clear AttributeError, so
        SQL aliases must be kept in strict sync with the dataclass field names.
        """
        return cls(**{k: row[k] for k in row})
